version: "2.2"

services: 

  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - app

  bd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=eduverde
      - MYSQL_ROOT_PASSWORD=eduverde

    networks:
      - app

networks:
  app: